/**
 * E2E-AGT: Agent settings live propagation — UI → Kaiad → Agent
 *
 * This test exercises the full settings-change pipeline in a single linear test:
 *
 *   1. Navigates to the Tenant Configuration page in the browser.
 *   2. Sets up an initial configuration and simulates an enrolled agent
 *      (a WebSocket connection from within the browser context).
 *   3. Cycles through every operator-visible setting one after the other,
 *      saving each change via the "Save tenant settings" button.
 *   4. After each save, checks TWO things:
 *        a. LIVE UPDATE — did the already-connected agent WebSocket receive
 *           updated settings without reconnecting? (Kaiad server push)
 *        b. RECONNECT UPDATE — after the agent closes and reopens its
 *           WebSocket, does the new hello frame carry the updated values?
 *
 * If (a) fails for any setting → that setting is logged as a bug in bugs.md
 * and the test is marked as failed (soft failure, so every setting is still
 * checked before the test ends).
 *
 * If (b) fails for any setting → the test fails hard (correctness regression).
 *
 * How it works:
 *   - page.routeWebSocket("** /realtime") intercepts WebSocket connections
 *     opened by the browser and provides mock hello frames sourced from the
 *     current serverSettings state variable (updated by the POST mock).
 *   - page.addInitScript() injects a tiny agent simulator into the browser that
 *     opens /realtime on page load and exposes helpers for re-connects.
 *   - page.route("** /api/v1/settings") provides a GET/POST mock that mutates
 *     serverSettings so subsequent WebSocket hello frames are always accurate.
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "@playwright/test";
import type { WebSocketRoute } from "@playwright/test";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const BUGS_MD_PATH = path.resolve(__dirname, "..", "bugs.md");

// ---------------------------------------------------------------------------
// Hello-frame builder — mirrors apps/api/src/agentHelloPayload.ts logic
// ---------------------------------------------------------------------------

interface MockSettings {
  tenantId: string;
  preferredExecutor?: "cursor" | "claude";
}

function buildHelloFromSettings(s: MockSettings): Record<string, unknown> {
  const hello: Record<string, unknown> = {
    type: "hello",
    service: "realtime",
    runtime: { backend: "docker" }
  };
  if (s.preferredExecutor) {
    hello["preferredExecutor"] = s.preferredExecutor;
  }
  return hello;
}

// ---------------------------------------------------------------------------
// Bug accumulator — written to bugs.md at the end of the test
// ---------------------------------------------------------------------------

interface BugEntry {
  id: string;
  title: string;
  affectedField: string;
  expected: string;
  observed: string;
}

function writeBugsMd(bugs: BugEntry[], ranAt: string): void {
  const lines: string[] = [
    `# Kaiad Agent Settings Propagation — Bug Report`,
    ``,
    `_Auto-generated by \`agent-settings-live-propagation.spec.ts\` at ${ranAt}_`,
    ``
  ];

  for (const bug of bugs) {
    lines.push(
      `## ${bug.id}: ${bug.title}`,
      ``,
      `| Field | Value |`,
      `|-------|-------|`,
      `| **Affected setting** | \`${bug.affectedField}\` |`,
      `| **Expected** | ${bug.expected} |`,
      `| **Observed** | ${bug.observed} |`,
      ``,
      `### Root cause`,
      ``,
      `The Kaiad API server persists the updated tenant settings to the store`,
      `when an operator saves changes via the UI, but does **not** push those`,
      `changes to agent WebSocket sessions that are already connected. The Go`,
      `agent's \`hello\` frame is only sent once — at connection time — so a`,
      `running agent never learns about setting changes until it reconnects.`,
      ``,
      `### Reproduction steps`,
      ``,
      `1. Start Kaiad and enroll a Go agent.`,
      `2. While the agent is connected, navigate to **Tenants → Configure**.`,
      `3. Change **${bug.affectedField}** and click **Save tenant settings**.`,
      `4. Observe: the connected agent does not receive any updated message.`,
      ``,
      `### Acceptance criteria`,
      ``,
      `After saving, Kaiad should send an updated \`hello\` (or a new`,
      `\`settings_update\` frame) to every WebSocket session belonging to the`,
      `affected tenant so agents update without requiring a reconnect.`,
      ``,
      `---`,
      ``
    );
  }

  fs.writeFileSync(BUGS_MD_PATH, lines.join("\n"), "utf8");
}

// ---------------------------------------------------------------------------
// Test
// ---------------------------------------------------------------------------

test.describe("E2E-AGT: Agent settings live propagation via UI → Kaiad → Agent", () => {
  test.beforeEach(async ({ page }) => {
    await page.addInitScript(() => {
      window.localStorage.setItem("sm_token", "dev-token");
    });
  });

  /**
   * Single linear test:
   *   setup → cycle all settings → verify live push (bug if missing) → verify reconnect
   */
  test(
    "E2E-AGT-001 all settings cycle: UI saves propagate to agent hello on reconnect; live push logged if absent",
    async ({ page }) => {
      const ranAt = new Date().toISOString();
      const bugs: BugEntry[] = [];

      // ── Shared mutable server state ─────────────────────────────────────
      // Updated each time the POST mock fires; read each time a WebSocket connects.
      let serverSettings: MockSettings = {
        tenantId: "t-1",
        preferredExecutor: undefined
      };

      // ── WebSocket route — intercepts the agent connection ────────────────
      // The injected browser script opens /realtime; we intercept, send hello.
      // The route handler sends a fresh hello on every new connection; `serverSettings`
      // is read at connection time (updated by the POST mock), so reconnects always
      // reflect the latest saved configuration.
      await page.routeWebSocket("**/realtime", (ws: WebSocketRoute) => {
        const hello = buildHelloFromSettings(serverSettings);
        ws.send(JSON.stringify(hello));

        ws.onMessage((msg: string | Buffer) => {
          try {
            const parsed = JSON.parse(msg.toString()) as Record<string, unknown>;
            // Ack every agent-to-server frame (heartbeat, log_event, etc.)
            if (parsed["type"] !== "ack") {
              ws.send(JSON.stringify({ type: "ack", accepted: true }));
            }
          } catch { /* ignore */ }
        });
      });

      // ── HTTP route mocks ─────────────────────────────────────────────────
      await page.route("**/api/v1/me", (route) => {
        if (route.request().method() !== "GET") return route.continue();
        return route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            id: "u-e2e",
            email: "e2e@example.com",
            role: "owner",
            tenantId: "t-1",
            memberships: [{ tenantId: "t-1", tenantName: "Default", role: "owner" }]
          })
        });
      });

      await page.route("**/api/v1/setup/status", (route) =>
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({ setupRequired: false, version: "0.1.0" })
        })
      );

      await page.route("**/api/v1/settings", async (route) => {
        const method = route.request().method();
        if (method === "GET") {
          return route.fulfill({
            status: 200,
            contentType: "application/json",
            body: JSON.stringify(serverSettings)
          });
        }
        if (method === "POST") {
          const body = JSON.parse(route.request().postData() ?? "{}") as Partial<MockSettings>;
          serverSettings = { 
            tenantId: body.tenantId ?? serverSettings.tenantId,
            preferredExecutor: body.preferredExecutor
          };
          return route.fulfill({
            status: 200,
            contentType: "application/json",
            body: JSON.stringify(serverSettings)
          });
        }
        return route.continue();
      });

      // Silence other API calls the UI makes
      await page.route("**/api/v1/settings/github-app", (route) =>
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            appId: null,
            appSlug: null,
            installUrl: null,
            privateKeyConfigured: false,
            webhookSecretConfigured: false
          })
        })
      );
      await page.route("**/api/v1/github/**", (route) =>
        route.fulfill({
          status: 404,
          contentType: "application/json",
          body: JSON.stringify({ code: "NOT_FOUND", message: "GitHub not configured" })
        })
      );
      await page.route("**/api/v1/agents/**", (route) =>
        route.fulfill({ status: 200, contentType: "application/json", body: JSON.stringify({ agents: [] }) })
      );
      await page.route("**/api/v1/session/**", (route) =>
        route.fulfill({
          status: 200,
          contentType: "application/json",
          body: JSON.stringify({
            id: "u-e2e",
            email: "e2e@example.com",
            role: "owner",
            tenantId: "t-1",
            memberships: [{ tenantId: "t-1", tenantName: "Default", role: "owner" }]
          })
        })
      );

      // ── Inject agent simulator into browser ──────────────────────────────
      // Opens a /realtime WebSocket on load, exposing helpers on window.
      await page.addInitScript(() => {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const w = window as any;
        w.__agentHellos = [] as Record<string, unknown>[];
        w.__agentPushes = [] as Record<string, unknown>[];

        function connectAgent(): WebSocket {
          const wsUrl = `ws://${location.host}/realtime`;
          const ws = new WebSocket(wsUrl);
          w.__agentWs = ws;
          ws.onmessage = (ev: MessageEvent<string>) => {
            try {
              const msg = JSON.parse(ev.data) as Record<string, unknown>;
              if (msg["type"] === "hello") {
                w.__agentHellos.push(msg);
              } else if (msg["type"] !== "ack") {
                w.__agentPushes.push(msg);
              }
              if (msg["type"] === "hello") {
                ws.send(
                  JSON.stringify({
                    type: "heartbeat",
                    agentId: "pw-agent-sim",
                    ts: new Date().toISOString(),
                    capacity: 4
                  })
                );
              }
            } catch { /* ignore */ }
          };
          return ws;
        }

        connectAgent();
        w.__connectAgent = connectAgent;
      });

      // ── Navigate to tenant config page ───────────────────────────────────
      await page.goto("/#tenant-config/t-1");
      await expect(page.getByRole("heading", { name: /Tenant Configuration/i })).toBeVisible({
        timeout: 10_000
      });
      await expect(page.getByLabel("Preferred executor")).toBeVisible();

      // Wait for the injected agent to receive its initial hello
      await expect
        .poll(() => page.evaluate(() => (window as unknown as { __agentHellos: unknown[] }).__agentHellos.length), {
          timeout: 6_000,
          message: "Initial hello not received by mock agent"
        })
        .toBeGreaterThan(0);

      // ── Shared step helpers ──────────────────────────────────────────────

      /** Get the last hello received by the mock agent (in browser). */
      async function getLastHello(): Promise<Record<string, unknown>> {
        const hellos = await page.evaluate(
          (): Record<string, unknown>[] =>
            (window as unknown as { __agentHellos: Record<string, unknown>[] }).__agentHellos
        );
        return hellos[hellos.length - 1]!;
      }

      /**
       * Wait up to `timeoutMs` for a frame on the existing WebSocket that
       * matches the predicate (returns null if none arrive).
       * This is the "live push" probe — the agent should NOT need to reconnect.
       */
      async function waitForLivePush(
        predicate: (msg: Record<string, unknown>) => boolean,
        timeoutMs = 3_000
      ): Promise<Record<string, unknown> | null> {
        const deadline = Date.now() + timeoutMs;
        while (Date.now() < deadline) {
          const pushes = await page.evaluate(
            (): Record<string, unknown>[] =>
              (window as unknown as { __agentPushes: Record<string, unknown>[] }).__agentPushes
          );
          const match = pushes.find(predicate);
          if (match) return match;
          // Also check if a new hello was pushed (some implementations re-send hello)
          const hellos = await page.evaluate(
            (): Record<string, unknown>[] =>
              (window as unknown as { __agentHellos: Record<string, unknown>[] }).__agentHellos
          );
          if (hellos.length > 1) {
            const lastHello = hellos[hellos.length - 1]!;
            if (predicate(lastHello)) return lastHello;
          }
          await page.waitForTimeout(250);
        }
        return null;
      }

      /**
       * Close the mock agent's WebSocket, reconnect, and return the new hello.
       * Mirrors what a real Go agent does after CloseActiveForReconnect().
       */
      async function reconnectAndGetHello(): Promise<Record<string, unknown>> {
        await page.evaluate(() => {
          const w = window as unknown as {
            __agentWs: WebSocket;
            __agentHellos: unknown[];
            __connectAgent: () => void;
          };
          w.__agentWs.close();
          w.__agentHellos = [];
        });
        await page.evaluate(() => {
          (window as unknown as { __connectAgent: () => void }).__connectAgent();
        });
        await expect
          .poll(
            () =>
              page.evaluate(
                () => (window as unknown as { __agentHellos: unknown[] }).__agentHellos.length
              ),
            { timeout: 6_000, message: "No hello received after agent reconnect" }
          )
          .toBeGreaterThan(0);
        return getLastHello();
      }

      /**
       * Core step: change a setting in the UI, save, then verify:
       *   a) live push to existing WebSocket (soft — logs bug on failure)
       *   b) correct hello after reconnect (hard — fails test on error)
       */
      async function settingStep(params: {
        stepName: string;
        bugId: string;
        uiAction: () => Promise<unknown>;
        /** Returns true when the frame reflects the updated setting. */
        helloMatcher: (hello: Record<string, unknown>) => boolean;
        expectedDescription: string;
        affectedField: string;
      }): Promise<void> {
        await test.step(params.stepName, async () => {
          // Reset push tracking before each change
          await page.evaluate(() => {
            (window as unknown as { __agentPushes: unknown[]; __agentHellos: unknown[] }).__agentPushes = [];
          });

          // 1. UI action (change one dropdown / input)
          await params.uiAction();

          // 2. Save
          await page.getByRole("button", { name: /Save tenant settings/i }).click();
          // Wait briefly for the POST response to complete
          await page.waitForTimeout(400);

          // 3. Live push check (3 s window)
          const pushedFrame = await waitForLivePush(params.helloMatcher);

          if (!pushedFrame) {
            bugs.push({
              id: params.bugId,
              title: `Setting change not pushed live to connected agent`,
              affectedField: params.affectedField,
              expected: `Kaiad sends an updated frame to the already-connected agent WebSocket within 3 s of the operator saving ${params.expectedDescription}`,
              observed: `No frame matching the updated value arrived on the existing WebSocket. The agent must disconnect and reconnect to receive the new setting.`
            });
          }

          // Soft assert — continues the test even on failure so all settings are checked
          expect.soft(
            pushedFrame,
            `[${params.bugId}] "${params.stepName}": No live push to connected agent. BUG logged to ${path.basename(BUGS_MD_PATH)}.`
          ).not.toBeNull();

          // 4. Reconnect and verify (hard check — must pass)
          const newHello = await reconnectAndGetHello();
          expect(
            params.helloMatcher(newHello),
            `[${params.bugId}-R] Wrong hello after reconnect for "${params.stepName}". Got: ${JSON.stringify(newHello)}`
          ).toBe(true);
        });
      }

      // ════════════════════════════════════════════════════════════════════
      // STEP 0: Initial setup — fill required fields and save baseline
      // ════════════════════════════════════════════════════════════════════
      await test.step("Setup: fill required fields and save initial settings", async () => {
        await page.getByLabel("Preferred executor").selectOption("");
        await page.getByRole("button", { name: /Save tenant settings/i }).click();
        await page.waitForTimeout(400);
      });

      // ════════════════════════════════════════════════════════════════════
      // CYCLE 1 — Preferred executor (preferredExecutor)
      // ════════════════════════════════════════════════════════════════════

      await settingStep({
        stepName: "Preferred executor: (none) → cursor",
        bugId: "BUG-AGT-004",
        affectedField: "preferredExecutor",
        expectedDescription: "preferredExecutor = cursor",
        uiAction: async () => { await page.getByLabel("Preferred executor").selectOption("cursor"); },
        helloMatcher: (h) => h["preferredExecutor"] === "cursor"
      });

      await settingStep({
        stepName: "Preferred executor: cursor → claude",
        bugId: "BUG-AGT-005",
        affectedField: "preferredExecutor",
        expectedDescription: "preferredExecutor = claude",
        uiAction: async () => { await page.getByLabel("Preferred executor").selectOption("claude"); },
        helloMatcher: (h) => h["preferredExecutor"] === "claude"
      });

      await settingStep({
        stepName: "Preferred executor: claude → (no preference)",
        bugId: "BUG-AGT-006",
        affectedField: "preferredExecutor",
        expectedDescription: "preferredExecutor cleared",
        uiAction: async () => { await page.getByLabel("Preferred executor").selectOption(""); },
        helloMatcher: (h) => h["preferredExecutor"] === undefined || h["preferredExecutor"] === null
      });

      // ── Write bugs.md (always, so last run's results are visible) ────────
      writeBugsMd(bugs, ranAt);

      // ── Final summary soft-check  ────────────────────────────────────────
      // Individual soft asserts above will already surface in Playwright output.
      // This message makes the summary more useful.
      if (bugs.length > 0) {
        console.warn(
          `\n⚠  ${bugs.length} live-push bug(s) logged to ${BUGS_MD_PATH}.\n` +
            bugs.map((b) => `   • ${b.id}: ${b.affectedField}`).join("\n") +
            "\n"
        );
      }
    }
  );
});
