{{- if .Values.kaiad.apiCredentialSecret.create }}
{{- if not .Values.kaiad.apiCredentialSecret.value }}
{{- fail "kaiad.apiCredentialSecret.create is true but kaiad.apiCredentialSecret.value is empty" }}
{{- end }}
{{- if not .Values.kaiad.apiCredentialSecret.name }}
{{- fail "kaiad.apiCredentialSecret.create is true but kaiad.apiCredentialSecret.name is empty" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kaiad.apiCredentialSecret.name }}
  labels: {{- include "kaiad-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.kaiad.apiCredentialSecret.value | quote }}
{{- end }}
